title: monkeyWang
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
name: 王伟
author: monkeyWang # add your name
author-img: avatar.jpg # add your photo
about-author: 现就职于杭州大搜车，担任前端开发工程师，做过底层业务，负责过公司架构设计。带过团队研究技术解决方案，爬坑无数。做过前端原生开发，也hold住后es6时代的发展变化；做过基于pc端的开发，也做过无线h5的研发；做过大型项目的自动化发布，单元测试，脚手架构建。 # add description
zhihu: monkey-wang-/activities # add your Twitter handle
juejin: 58de5a49ac502e006cfb35e9 # add your Facebook handle
github: monkeyWangs # add your Github handle
linkedin: # add your Linkedin handle
email: 2424880409@qq.com # add your Email address
tel: 18668218226

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
